### ISSUE TITLE
Error crictal cant play

### ISSUE THREAD

**Issue by ssaagamemer** [ThatOneBepis/Infinitodustry-future#9]
[last_log.txt](https://github.com/ThatOneBepis/Infinitodustry/files/5793926/last_log.txt)
Oppo a37fw Android 5.0.1
Not crash but error

**Comment by ssaagamemer** [comment]
I can fix but not all

**Comment by ThatOneBepis** [comment]
i have in mind fixing it, but am overcrowded with other issues

**Comment by ssaagamemer** [comment]
Ok thx
